#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Mar 05, 2022 08:51:13 PM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import questionnaire_main_support

class login:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("621x450+335+104")
        top.minsize(120, 1)
        top.maxsize(2724, 881)
        top.resizable(1,  1)
        top.title("login")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.177, rely=0.178, relheight=0.589
                , relwidth=0.623)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.003, rely=0.004, height=58, width=386)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#8386fc")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 14 -weight bold -slant italic")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''LOGIN''')

        self.username_lable = tk.Label(self.Frame1)
        self.username_lable.place(relx=0.026, rely=0.34, height=24, width=106)
        self.username_lable.configure(activebackground="#f9f9f9")
        self.username_lable.configure(activeforeground="black")
        self.username_lable.configure(background="#d9d9d9")
        self.username_lable.configure(compound='left')
        self.username_lable.configure(disabledforeground="#a3a3a3")
        self.username_lable.configure(foreground="#000000")
        self.username_lable.configure(highlightbackground="#d9d9d9")
        self.username_lable.configure(highlightcolor="black")
        self.username_lable.configure(text='''Username:''')

        self.password_lable = tk.Label(self.Frame1)
        self.password_lable.place(relx=0.026, rely=0.566, height=24, width=105)
        self.password_lable.configure(activebackground="#f9f9f9")
        self.password_lable.configure(activeforeground="black")
        self.password_lable.configure(background="#d9d9d9")
        self.password_lable.configure(compound='left')
        self.password_lable.configure(disabledforeground="#a3a3a3")
        self.password_lable.configure(foreground="#000000")
        self.password_lable.configure(highlightbackground="#d9d9d9")
        self.password_lable.configure(highlightcolor="black")
        self.password_lable.configure(text='''Password:''')

        self.username_entry = tk.Entry(self.Frame1)
        self.username_entry.place(relx=0.362, rely=0.566, height=20
                , relwidth=0.424)
        self.username_entry.configure(background="white")
        self.username_entry.configure(disabledforeground="#a3a3a3")
        self.username_entry.configure(font="TkFixedFont")
        self.username_entry.configure(foreground="#000000")
        self.username_entry.configure(highlightbackground="#d9d9d9")
        self.username_entry.configure(highlightcolor="black")
        self.username_entry.configure(insertbackground="black")
        self.username_entry.configure(selectbackground="blue")
        self.username_entry.configure(selectforeground="white")

        self.login_btn = tk.Button(self.Frame1)
        self.login_btn.place(relx=0.388, rely=0.755, height=34, width=87)
        self.login_btn.configure(activebackground="#ececec")
        self.login_btn.configure(activeforeground="#000000")
        self.login_btn.configure(background="#859ffa")
        self.login_btn.configure(command=questionnaire_main_support.login_func)
        self.login_btn.configure(compound='left')
        self.login_btn.configure(disabledforeground="#a3a3a3")
        self.login_btn.configure(font="-family {Segoe UI} -size 11")
        self.login_btn.configure(foreground="#ffffff")
        self.login_btn.configure(highlightbackground="#d9d9d9")
        self.login_btn.configure(highlightcolor="black")
        self.login_btn.configure(pady="0")
        self.login_btn.configure(text='''Submit''')

        self.password_entry = tk.Entry(self.Frame1)
        self.password_entry.place(relx=0.362, rely=0.34, height=20
                , relwidth=0.424)
        self.password_entry.configure(background="white")
        self.password_entry.configure(disabledforeground="#a3a3a3")
        self.password_entry.configure(font="TkFixedFont")
        self.password_entry.configure(foreground="#000000")
        self.password_entry.configure(highlightbackground="#d9d9d9")
        self.password_entry.configure(highlightcolor="black")
        self.password_entry.configure(insertbackground="black")
        self.password_entry.configure(selectbackground="blue")
        self.password_entry.configure(selectforeground="white")

class menu:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("621x450+376+86")
        top.minsize(120, 1)
        top.maxsize(2724, 881)
        top.resizable(1,  1)
        top.title("menu")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.0, rely=0.0, height=71, width=624)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#8386fc")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 20 -weight bold -slant italic")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Questionnaire''')

        self.ask_questions_btn = tk.Button(self.top)
        self.ask_questions_btn.place(relx=0.242, rely=0.422, height=44
                , width=307)
        self.ask_questions_btn.configure(activebackground="#ececec")
        self.ask_questions_btn.configure(activeforeground="#000000")
        self.ask_questions_btn.configure(background="#859ffa")
        self.ask_questions_btn.configure(command=questionnaire_main_support.to_questionnaire_func)
        self.ask_questions_btn.configure(compound='left')
        self.ask_questions_btn.configure(disabledforeground="#a3a3a3")
        self.ask_questions_btn.configure(font="-family {Segoe UI} -size 12")
        self.ask_questions_btn.configure(foreground="#ffffff")
        self.ask_questions_btn.configure(highlightbackground="#d9d9d9")
        self.ask_questions_btn.configure(highlightcolor="black")
        self.ask_questions_btn.configure(pady="0")
        self.ask_questions_btn.configure(text='''Ask questions''')

        self.statistics_btn = tk.Button(self.top)
        self.statistics_btn.place(relx=0.242, rely=0.6, height=44, width=307)
        self.statistics_btn.configure(activebackground="#ececec")
        self.statistics_btn.configure(activeforeground="#000000")
        self.statistics_btn.configure(background="#859ffa")
        self.statistics_btn.configure(command=questionnaire_main_support.to_statistics_func)
        self.statistics_btn.configure(compound='left')
        self.statistics_btn.configure(disabledforeground="#a3a3a3")
        self.statistics_btn.configure(font="-family {Segoe UI} -size 12")
        self.statistics_btn.configure(foreground="#ffffff")
        self.statistics_btn.configure(highlightbackground="#d9d9d9")
        self.statistics_btn.configure(highlightcolor="black")
        self.statistics_btn.configure(pady="0")
        self.statistics_btn.configure(text='''Statistics''')

        self.TSeparator1 = ttk.Separator(self.top)
        self.TSeparator1.place(relx=0.177, rely=0.333,  relwidth=0.628)

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.37, rely=0.267, height=21, width=144)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''MENU''')

        self.logout_btn = tk.Button(self.top)
        self.logout_btn.place(relx=0.242, rely=0.778, height=44, width=307)
        self.logout_btn.configure(activebackground="#ececec")
        self.logout_btn.configure(activeforeground="#000000")
        self.logout_btn.configure(background="#859ffa")
        self.logout_btn.configure(command=questionnaire_main_support.logout_func)
        self.logout_btn.configure(compound='left')
        self.logout_btn.configure(disabledforeground="#a3a3a3")
        self.logout_btn.configure(font="-family {Segoe UI} -size 12")
        self.logout_btn.configure(foreground="#ffffff")
        self.logout_btn.configure(highlightbackground="#d9d9d9")
        self.logout_btn.configure(highlightcolor="black")
        self.logout_btn.configure(pady="0")
        self.logout_btn.configure(text='''Logout''')

class Questionnaire:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("621x450+336+105")
        top.minsize(120, 1)
        top.maxsize(2724, 881)
        top.resizable(1,  1)
        top.title("Questionnaire")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.0, rely=0.0, height=71, width=624)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#8386fc")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 20 -weight bold -slant italic")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Questionnaire''')

        self.to_menu_btn = tk.Button(self.top)
        self.to_menu_btn.place(relx=0.837, rely=0.889, height=34, width=77)
        self.to_menu_btn.configure(activebackground="#ececec")
        self.to_menu_btn.configure(activeforeground="#000000")
        self.to_menu_btn.configure(background="#859ffa")
        self.to_menu_btn.configure(command=questionnaire_main_support.to_menu_func)
        self.to_menu_btn.configure(compound='left')
        self.to_menu_btn.configure(cursor="fleur")
        self.to_menu_btn.configure(disabledforeground="#a3a3a3")
        self.to_menu_btn.configure(font="-family {Segoe UI} -size 11")
        self.to_menu_btn.configure(foreground="#ffffff")
        self.to_menu_btn.configure(highlightbackground="#d9d9d9")
        self.to_menu_btn.configure(highlightcolor="black")
        self.to_menu_btn.configure(pady="0")
        self.to_menu_btn.configure(text='''Back''')

class Statistics:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+310+117")
        top.minsize(120, 1)
        top.maxsize(2724, 881)
        top.resizable(1,  1)
        top.title("Statistics")
        top.configure(background="#d9d9d9")

        self.top = top

        self.to_menu_btn = tk.Button(self.top)
        self.to_menu_btn.place(relx=0.817, rely=0.889, height=34, width=77)
        self.to_menu_btn.configure(activebackground="#ececec")
        self.to_menu_btn.configure(activeforeground="#000000")
        self.to_menu_btn.configure(background="#859ffa")
        self.to_menu_btn.configure(compound='left')
        self.to_menu_btn.configure(cursor="fleur")
        self.to_menu_btn.configure(disabledforeground="#a3a3a3")
        self.to_menu_btn.configure(font="-family {Segoe UI} -size 11")
        self.to_menu_btn.configure(foreground="#ffffff")
        self.to_menu_btn.configure(highlightbackground="#d9d9d9")
        self.to_menu_btn.configure(highlightcolor="black")
        self.to_menu_btn.configure(pady="0")
        self.to_menu_btn.configure(text='''Back''')

def start_up():
    questionnaire_main_support.main()

if __name__ == '__main__':
    questionnaire_main_support.main()




